### ISSUE TITLE
Binary not starting

### ISSUE THREAD

**Issue by phfu** [Christian-ALLEGRE/WsjtxAdiMerger#1]
Hi Christian, 
After downloading the complete zip, I started the .exe in the sub folder.
It required a new version for the .net, that I then installed.
After that, when I double click on the .exe, it seems to start but after a few seconds, nothing, no windows, no message.

Regards 73 !
Philippe  :)

**Comment by Christian-ALLEGRE** [comment]
Thanks for this bug discovery. It was due to the Lang registry variable that was used when not initialized !!!!
Fixed now in V1.1a (2024/02/17 16:00)
